import os
PAGES = r'D:\my-wiki\知识库'

# Page: 开发路线图
lines = []
lines.append('---')
lines.append('title: Agent Runtime 开发路线图')
lines.append('created: \"2026-07-10\"')
lines.append('updated: \"2026-07-10\"')
lines.append('type: note')
lines.append('tags: [roadmap, development-plan, phase-planning]')
lines.append('---')
lines.append('')
lines.append('# Agent Runtime 开发路线图')
lines.append('')
lines.append('## 开发哲学')
lines.append('')
lines.append('不用代码行数衡量进度。用四个问题：')
lines.append('')
lines.append('1. 抽象是否更稳定？（对象、边界、职责是否更清晰）')
lines.append('2. 系统是否真正跑起来？（哪怕功能很少，但能持续执行）')
lines.append('3. 是否能服务真实工作？（先服务 Wiki 维护 Agent 和文旅策划 Agent）')
lines.append('4. 系统是否因为真实使用而变得更简单，而不是更复杂？')
lines.append('')
lines.append('这不是一个产品开发项目，而是一个长期 Research Engineering Project。真正要沉淀的不是某个版本的代码，而是一套能够不断诞生 Agent、不断吸收新模型、不断适应新工具的工程体系。')
lines.append('')
lines.append('## Phase 0：Schema Extraction（1小时）')
lines.append('')
lines.append('### Step 0a — Perspective + Object Rule')
lines.append('perspective.md：本系统以 Runtime 为观察视角。')
lines.append('object-rule.md：Runtime 能寻址 + 查询状态 + 执行操作 = 一等对象。')
lines.append('')
lines.append('### Step 0b — Object Discovery')
lines.append('从现有 75 页 knowledge + 7 个 protocol + hot.md 中发现对象。')
lines.append('不设计，只发现。不定义 Schema，只列出对象。')
lines.append('')
lines.append('### Step 0c — Ontology v0.1')
lines.append('每个对象：一句话定义、生命周期、Owner、Consumer。不含 Schema。')
lines.append('')
lines.append('## Phase 1：State Runtime（1-2周）')
lines.append('')
lines.append('新建：state/ 目录 + JSON schema + state-manager/ + event-bus/ + policy.md')
lines.append('State Manager：lock/validate/merge/history/recover')
lines.append('Exit：脚本创建 Task、更新 State、写入 Memory、发 Event——不需要 AI')
lines.append('')
lines.append('## Phase 2：Knowledge + Capability（2-4周）')
lines.append('')
lines.append('四种 Graph：Knowledge/Capability/Workflow/Dependency')
lines.append('Memory 五层：Working/Session/Project/Semantic/Archive')
lines.append('Protocol 格式：State->JSON, Protocol->YAML, Config->TOML')
lines.append('Exit：Agent 自主完成 收 URL -> 入库 -> 生成知识页')
lines.append('')
lines.append('## Phase 3：Planner + Application（4-6周）')
lines.append('')
lines.append('Planner 动态编排，不是固定 YAML 模板')
lines.append('首个 Application：Wiki 维护 Agent')
lines.append('Exit：Agent 生产环境持续运行 7 天无人工干预')
lines.append('')
lines.append('## Phase 4：Interface（未来）')
lines.append('')
lines.append('Agent Workspace UI：隐藏所有底层细节')
lines.append('Exit：人类可通过 UI 而非文件系统操作系统')
lines.append('')
lines.append('总计约 2-3 个月到 Phase 3 完成。')

with open(os.path.join(PAGES, 'Agent Runtime 开发路线图.md'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('OK: 开发路线图')
